### ISSUE TITLE
Aplikacja startowa

### ISSUE THREAD

**Issue by mykulyak** [g3f4-xyz/lifeapp#5]
Aplikacja powinna uruchamiać się (może być pusta strona), powinno dać się zlintować, wygenerować dokumentację. Konfiguracja WebPack powinna umożliwiać uruchomienie aplikacji w trybie deweloperskim oraz zbudowanie paczki. Generalnie to co robimy w innych projektach.

**Comment by G3F4** [comment]
Rezygnujemy z react-create-app.
Nowe treść zadania:
Podstawowa struktura projektu która na razie będzie zawierała jedynie:
- inicjalny plik package.json z minimalną ilością zależności aby odpalić projekt
- strukturę katalogów dla client'a 
- index.html z linkowaniem do paczki
oraz 
Bazową konfiguracje webpack'a zawierającą:
- jeden entry point(app.js albo index.js)
- serwer developerski

**Comment by G3F4** [comment]
https://github.com/g3f4-xyz/lifeapp/commit/f16876025185d8993f2a5da8dab111fd479ad7a5

Podstawowa konfiguracja webpack'a oparta na dokumentacji webpack'a 2(https://webpack.js.org/guides/hmr-react/)

Po zaciągnięciu kodu odpalamy:
npm i
npm start
i przechodzimy w przeglądarce na localhost:8080

Aplikacja ma ustawiony hot-reload. Enjoy!
